### ISSUE TITLE
_pickle.UnpicklingError: invalid load key, 'v'.

### ISSUE THREAD

**Issue by DinnerWhen** [hulitaotom/Joint-Multi-Scale-Tone-Mapping-and-Denoising-for-HDR-Image-Enhancement#1]
When run main_test.py,"_pickle.UnpicklingError: invalid load key, 'v'.". Could you help?

**Comment by HugeRoll** [comment]
check if the model is damaged(just check the file size). you can download the .pth independently

**Comment by DinnerWhen** [comment]
Thanks!
